### ISSUE TITLE
LEDE with SNAPSHOT is missing

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#10]
i cant build LEDE Snapshot Firmware any more.

**Comment by FreifunkUFO** [comment]
screenshot

![freifunk-jeke](https://user-images.githubusercontent.com/2579265/32006248-8a5ec4ae-b9a6-11e7-9a57-43e3fc1dc308.jpg)

**Comment by aparcar** [comment]
see https://github.com/aparcar/gsoc17-attended-sysupgrade/issues/57

**Comment by ilario** [comment]
Maybe related to libremesh/lime-sdk#2 ?
