### ISSUE TITLE
error messages of previous submissions remain visible

### ISSUE THREAD

**Issue by dangowrt** [aparcar/jefe#11]
An error message triggered by a previous attempt (e.g. "could not find package 'xxx' for requested target") remains visible for ever.
Fix: Everytime the 'Create Image...' button is being pressed, all previous error messages should by cleared.

**Comment by dangowrt** [comment]
... same for previous advanced results box with the list of files which isn't cleared on subsequent presses of the 'Create image...' button.

**Comment by aparcar** [comment]
this was solved a while ago
