### ISSUE TITLE
use 'hand holding pen' icon for signature rather than key

### ISSUE THREAD

**Issue by dangowrt** [aparcar/jefe#12]
in the list of previously created images the 'key' symbol for the signature file is a bit confusing imho.
i thought of something like 'hand singing official paper' or the classic 'document with seal' symbol often used for cryptographic certificates would be better. or maybe a stamp?

weird that there is no unicode symbol for that. the closest i could find are
# 🖋
# 📋

**Comment by aparcar** [comment]
So far I used octicons instead of emojis, maybe you can find something appealing here?

https://octicons.github.com/

**Comment by aparcar** [comment]
switched to https://octicons.github.com/icon/verified/
