### ISSUE TITLE
model search: also search for target/subtarget/profile

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#16]
when i search for "x86" there is no answer. atm i have to search for "generic".

**Comment by FreifunkUFO** [comment]
its done by the server: https://github.com/aparcar/gsoc17-attended-sysupgrade/blob/master/utils/database.py#L428

**Comment by aparcar** [comment]
https://github.com/aparcar/gsoc17-attended-sysupgrade/commit/68044cf35e6299f6c183dcd522e35695314c10a7 fixed here
