### ISSUE TITLE
Merge in upgrade-server repo

### ISSUE THREAD

**Issue by aparcar** [aparcar/jefe#17]
Currently the upgrade-server repo contains "jefe" as well[1]. Would you suggest to merge the project in the upgrade-server or keep it separated?

@FreifunkUFO @ilario @dangowrt

[1]: http://ledeupdate.planetexpress.cc/imagebuilder

**Comment by aparcar** [comment]
as posted in the README.md

**Comment by FreifunkUFO** [comment]
no-one was answering yet.

which README.md do you mean?

**Comment by aparcar** [comment]
the chef readme, however I just decided to keep things separated for the moment.
