### ISSUE TITLE
make some tickets to support freifunk

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#24]
@aparcar was asking about supporting freifunk mesh firmwares. and their packagelists.
for these many freifunk networks we need many presets, packagelists, "distributions" (fi gluon and berlin are built on LEDE, but with big patch-lists)  and/or firmwares.
so we would need many tickets, at least one for each freifunk-approach

**Comment by aparcar** [comment]
To support the different patched "distributions" the upgrade server need's all the ImageBuilders. We need to ask the FF-communities to create them as well and store them in the same structure as on official servers

@mwarning

**Comment by FreifunkUFO** [comment]
at least some freifunk distributions are also working with standard-lede-imagebuilder.. but mostly there are patched. f.i. atm  freifunk-meshkit in leipzig has imagebuilder-builds with disabled ksymbols (to support common hardware, like cpe510).
you could try it with http://gadow.freifunk.net:8004/srv2/lede/lede-20171030/bin/targets/ar71xx/generic/lede-imagebuilder-SNAPSHOT-ar71xx-generic.Linux-x86_64.tar.xz

**Comment by aparcar** [comment]
Specially patched imagebuilders are supported as long as they follow the official naming. 
An example can be found [here](https://chef.libremesh.org/#87467e0d4ab5607)

For snapshots is therefore important to disable the following two options:
```#CONFIG_VERSION_FILENAMES=y
# CONFIG_VERSION_CODE_FILENAMES=y
```

@mwarning @2tata if possible please provide patched imagebuilders in the official structure to enable custom image building via chef.

**Comment by FreifunkUFO** [comment]
so, we would need at least one ticket for each freifunk-firmware-distribution? (weimar, berlin, leipzig, jena, bielefeld, gluon) details should be discussed there. 

we could start realization with firmware which is able to use unpatched openwrt/lede and then have a look about their configuration (which one are zeroconfig firmwares?). and ask other firmwares developers about their imagebuilder and details.

**Comment by FreifunkUFO** [comment]
i started with 
leipzig https://github.com/libremesh/chef/issues/30
and 
gluon https://github.com/libremesh/chef/issues/29
and 
berlin https://github.com/libremesh/chef/issues/31

**Comment by aparcar** [comment]
should we close this "meta issue" and focus on the specific ones?

**Comment by FreifunkUFO** [comment]
ticket issue was to open tickets for freifunk. there are only 3 atm. what about f.i. @mwarning or weimar or jena @egon0 ?

**Comment by mtippmann** [comment]
@FreifunkUFO maybe it's easier to implement a configuration file that contains all required community-specific urls so every community can setup their own instance of chef/update-server? In Weimar we'll probably need custom fields (nodenumber hack) and we also can't use the generic imagebuilder/sdk at the moment - so I don't think it's worthwhile to add us to the list at the moment.

**Comment by egon0** [comment]
Jena will use plain libremesh with a network-profile soon, no need to do anything to support the old monkeypatched legacy Firmware.

**Comment by aparcar** [comment]
Can Iclose this?

**Comment by aparcar** [comment]
Please open ASU specific issues here: https://github.com/aparcar/asu/
Please open interface specific issues here: https://gitlab.com/openwrt/web/firmware-selector-openwrt-org

Chef is no longer developed.
