### ISSUE TITLE
impossible build image for ubiquiti loco xw

### ISSUE THREAD

**Issue by digitigrafo** [aparcar/jefe#28]
say: image building.

In console of browser (firefox 57):

chef.js:464:4
GETXHR
https://ledeupdate.planetexpress.cc/api/build-request/e83cb1e07ec8
[HTTP/1.1 202 ACCEPTED 45ms]
building
chef.js:464:4
GETXHR
https://ledeupdate.planetexpress.cc/api/build-request/e83cb1e07ec8
[HTTP/1.1 202 ACCEPTED 42ms]
....

for infinite time.
![istantanea_2017-12-17_15-30-28](https://user-images.githubusercontent.com/11573104/34080496-4d88a032-e33f-11e7-9fbd-1f38f8886345.png)

**Comment by aparcar** [comment]
@digitigrafo I recently tried some new stuff and seems to cause some problems. I reset parts of the database and build the image, please try yourself.
https://chef.libremesh.org/#2478b9c37ce2b52

**Comment by digitigrafo** [comment]
yes! thanks. now is working.
