### ISSUE TITLE
support freifunk berlin

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#31]
berlin is using self-build firmware with large patchsets, own openwrt/lede-packages and own webui-wizard for configuration.

see https://github.com/freifunk-berlin/firmware and packages are at https://github.com/freifunk-berlin/firmware-packages

**Comment by aparcar** [comment]
@andrenarchy ping

**Comment by andrenarchy** [comment]
Also looping in @SvenRoederer and @booo from Berlin. :)

**Comment by aparcar** [comment]
@andrenarchy could you please provide the imagebuilders of your current release?

**Comment by SvenRoederer** [comment]
they can be found in https://buildbot.berlin.freifunk.net/buildbot/stable/1.0.0/

**Comment by aparcar** [comment]
Hi @SvenRoederer , do you mind changing the folder structure to the official format of `target/subtarget` instead of `target-subtarget`? Then it'd be compatible which the server backend

**Comment by aparcar** [comment]
Please open ASU specific issues here: https://github.com/aparcar/asu/
Please open interface specific issues here: https://gitlab.com/openwrt/web/firmware-selector-openwrt-org

Chef is no longer developed.
