### ISSUE TITLE
support freifunk bielefeld

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#32]
bielefeld is using an own freifunk-firmware (of course openwrt/lede)
https://github.com/freifunk-bielefeld/firmware
some special packages.. two patchset-directories..

**Comment by FreifunkUFO** [comment]
ping @mwarning, what do you think. would it be possible?

https://github.com/libremesh/chef/issues/24

**Comment by mwarning** [comment]
not sure, I have to try. I was sick over last week.

**Comment by aparcar** [comment]
@mwarning could you please provide the imagebuilders of your current release?

**Comment by aparcar** [comment]
@mwarning ping

**Comment by mwarning** [comment]
@aparcar we still struggle to get the next release ready for the release..

**Comment by aparcar** [comment]
@mwarning any updates?

**Comment by mwarning** [comment]
this weekend

**Comment by aparcar** [comment]
Please follow the official folder structure `[version]/targets/[target]/[subtarget]/` if possible :+1:

**Comment by mwarning** [comment]
ok, we finally had out 1.0.0 release. Let's see what needs to be done. :-)
@aparcar is the structure for the images? We have them all in one folder.

**Comment by aparcar** [comment]
I need the image builder in the previously mentioned structure for all targets you'd like to support

**Comment by mwarning** [comment]
Would this do? http://firmware.freifunk-bielefeld.de/freifunk/firmware/1.0.0/targets/

**Comment by aparcar** [comment]
Perfekt!

**Comment by aparcar** [comment]
@mwarning actually sorry, the structure is not perfect yet. The [meta-imagebuilder](https://github.com/aparcar/meta-imagebuilder/) validates downloaded imagebuilders via checksums and [gpg](https://github.com/aparcar/meta-imagebuilder/blob/master/meta#L64). I could disable it specifically for FF Bielefeld, but a nicer solution would be you sign the created imagebuilders as well

**Comment by mwarning** [comment]
hm, what do I have to do? What gpg key has to be used?

**Comment by aparcar** [comment]
Nevermind, I'll use https and adapt the meta imagebuilder :)

**Comment by mwarning** [comment]
Fine with lazy myself. :D

**Comment by aparcar** [comment]
Please open ASU specific issues here: https://github.com/aparcar/asu/
Please open interface specific issues here: https://gitlab.com/openwrt/web/firmware-selector-openwrt-org

Chef is no longer developed.
