### ISSUE TITLE
easy way to add custom /etc/config files

### ISSUE THREAD

**Issue by ghost** [aparcar/jefe#34]
Would like the ability to upload custom /etc/config files to be included in the resulting firmware binary image

**Comment by aparcar** [comment]
Yes. Create a network profile and merge it into the official libre mesh repo. The server will build packages put of it which are installable. 

A different approach to allow per image different settings exceeds the current scope of the image server. Hard to manage versions and outdated images

**Comment by ilario** [comment]
You can take as an example the other network-profiles, they all have files in /etc/config, doesn matter if it's lime-defaults or another file.

**Comment by aparcar** [comment]
the created packages are [here](http://repo.libremesh.org/network-profiles/), you could even install multible of them with different ssh-keys or whatever you need

**Comment by ghost** [comment]
Thanks for your responses!
