### ISSUE TITLE
"tr-queue-position" can't be naturally translated to Catalan

### ISSUE THREAD

**Issue by rogerpueyo** [aparcar/jefe#37]
The string "tr-queue-position", which in English is translated as "You are in build queue position " (e.g. "You are in build queue position 123"), in Catalan would be "Us trobeu a la posició 123 de la cua de compilació". I can't find an equivalent sentence that has the number at the very end and sounds natural.

Can the "tr-queue-position" be modified to include the queue position inside the string?

**Comment by aparcar** [comment]
good question, currently I'm researching if there's a better way for i18n. Using `po` files could be a better approach and by that supporting `%s` stuff as well.

**Comment by aparcar** [comment]
I could implement the %s formating myself, however as the current version of image server does not support queue position estimation (just yet) you can leave it to something translated to "You're in building queue" without any number.

**Comment by Nikerabbit** [comment]
In fact, this cannot be properly translated to any language currently, because trailing whitespace is not supported in translatewiki.net.

**Comment by aparcar** [comment]
The new interface uses different strings.

Please open ASU specific issues here: https://github.com/aparcar/asu/
Please open interface specific issues here: https://gitlab.com/openwrt/web/firmware-selector-openwrt-org

Chef is no longer developed.
