### ISSUE TITLE
hyperlink to network profile not working

### ISSUE THREAD

**Issue by ghost** [aparcar/jefe#39]
according to https://github.com/libremesh/chef/blob/master/chef.html#L97 there is a hyperlink to https://github.com/libremesh/network-profiles/

I think this is a good idea but for some reason neither firefox nor chrome is not rendering the hyperlink

![2018-02-18-034650_532x136_scrot](https://user-images.githubusercontent.com/2603422/36347703-6c85a39a-145e-11e8-840e-b3e27c5864e6.png)

**Comment by aparcar** [comment]
Thanks, I think the link is removed by the translation system. I think we need to add a span inside the href and move the translation id away from the label to the span (inside the href).

@pedro-nonfree are you up for an PR?
