### ISSUE TITLE
chrome/chromium: bad rendering of advanced checkbox

### ISSUE THREAD

**Issue by ghost** [aparcar/jefe#40]
![2018-02-18-034809_410x228_scrot](https://user-images.githubusercontent.com/2603422/36347711-8c312eb2-145e-11e8-9775-dcfa0f1e6848.png)

**Comment by aparcar** [comment]
We could move the *Advanced* button to the navbar, currently the checkbox is kind a improvised without using bootstrap correctly. 

@pedro-nonfree are you up for a PR?
