### ISSUE TITLE
fix the link to logfile when "could not find package.." 

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#5]
a link is existing, but defect URL

**Comment by aparcar** [comment]
could you please provide used target subtarget combo?

**Comment by FreifunkUFO** [comment]
it seems to be on ALL target subtarget combos.

also see https://github.com/aparcar/jefe/commit/dafb152e861f08d425cf6d6a802544219df1f69c about deleting the link to the log..

**Comment by aparcar** [comment]
so the logfile is only for the imagebuilder, the internal server log is not represented there.
the commit you mentioned above should hide the build log on any location the imagebuilder wasn't even started due to a bad request
