### ISSUE TITLE
Support of disro/version descriptions and aliases 

### ISSUE THREAD

**Issue by aparcar** [aparcar/jefe#59]
The new API offers some further information about versions and distributions, see an example below. Both should be included (if available) in the new chef design to help the user

https://as-test.stephen304.com/api/versions
https://as-test.stephen304.com/api/distros

**Comment by edvm** [comment]
@aparcar working on this :+1:

**Comment by aparcar** [comment]
The current API implementation returns an array, I could change that to return a dict like this
```
{
    "openwrt": { "alias": OpenWrt", "latest": "18.06.0" },
    "lime": { "alias": "LibreMesh", "latest": "17.06" }
}
```

**Comment by edvm** [comment]
@aparcar its fine that the API returns a list of elements, please dont change it :)

**Comment by aparcar** [comment]
The [current dev version of Chef](https://as-test.stephen304.com/chef/) already supports this,
![image](https://user-images.githubusercontent.com/16000931/45181493-543b3580-b1ba-11e8-888a-5dc4247fab7d.png)
