### ISSUE TITLE
de-select packages

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#6]
in meshkit (and imagebuilder) there is the possibility to mark packages as "not to install" with a "minus"
this is sometimes important to get rid of unwanted packages, which are in the dependecies of other, needed packages.

for instance: i want to have libremesh (package lime-full) without "lime-proto-wan" and "lime-hwd-openwrt-wan" to avoid the usage of dhcp-client on wan-interface.

lime-full
-lime-proto-wan
-lime-hwd-openwrt-wan

**Comment by aparcar** [comment]
please see this thread. https://github.com/libremesh/lime-packages/issues/175
force unloading of dependencies look more like bad set dependencies.
jefe will only install packages in the list and it dependencies
