### ISSUE TITLE
Language selector is broken

### ISSUE THREAD

**Issue by agusalex** [aparcar/jefe#63]
![image](https://user-images.githubusercontent.com/15642727/45910879-3d642800-bde3-11e8-9387-a466e65321f3.png)
Changing language does nothing, it stays on english.

**Comment by agusalex** [comment]
The issue seems to be that the method translate() cannot be found by index.html 
`(index):27 Uncaught TypeError: translate is not a function
    at HTMLSelectElement.onchange ((index):27)`

**Comment by aparcar** [comment]
Thanks, I'll look into that!

**Comment by aparcar** [comment]
I don't know when, but I think the issue was fixed some time ago
