### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by Roland-B** [aparcar/jefe#64]
Says building but never finishes. Also WRT32X snapshot build manifest failures previous to this that, that don't clear after 24hrs for  / mvebu / cortexa9 / .

Thanks.

**Comment by Roland-B** [comment]
https://as-test.stephen304.com/download/faillogs/faillog-96e8f4729eba.txt
https://as-test.stephen304.com/download/faillogs/faillog-b7bba45f737e.txt

Thanks.

**Comment by Roland-B** [comment]
https://as-test.stephen304.com/download/faillogs/faillog-8b81e8b31f12.txt
https://as-test.stephen304.com/download/faillogs/faillog-b7bba45f737e.txt

**Comment by aparcar** [comment]
I have to investigate a bit more as it seems to be a general problem for snapshots...
Thanks for testing and please be patient

**Comment by Roland-B** [comment]
okidoke, thanks for the update.

**Comment by Roland-B** [comment]
Still have issues after your update on openwrt forum. Thanks for trying though (Roland B).
https://as-test.stephen304.com/download/faillogs/faillog-8b81e8b31f12.txt

**Comment by aparcar** [comment]
Looks like `wpad-mini` was renamed to `wpad-mini`?

```
Collected errors:
 * check_data_file_clashes: Package wpad-basic wants to install file /mnt/worker/worker1/imagebuilder/openwrt/snapshots/mvebu/cortexa9/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root-mvebu/usr/sbin/hostapd
	But that file is already provided by package  * wpad-mini
 * check_data_file_clashes: Package wpad-basic wants to install file /mnt/worker/worker1/imagebuilder/openwrt/snapshots/mvebu/cortexa9/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root-mvebu/usr/sbin/wpa_supplicant
	But that file is already provided by package  * wpad-mini
 * check_data_file_clashes: Package wpad-basic wants to install file /mnt/worker/worker1/imagebuilder/openwrt/snapshots/mvebu/cortexa9/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root-mvebu/usr/sbin/wpad
	But that file is already provided by package  * wpad-mini
 * opkg_install_cmd: Cannot install package wpad-basic.
```
I'm on it!

**Comment by Roland-B** [comment]
Like a car bonnet!! :) Brilliant, thanks v much bud.  

This is the only thing i can find relating to this lately...
https://github.com/openwrt/openwrt/commit/80c61c161ac5943137ade233d62cf89d746de5a2#diff-537f70c94a22713f365b47c7efe9ff0e

hopefully this helps?

Have tried removing wpad-mini from the package list when building a snapshot and it does complile and used wpad-basic, but get a warning the image produced is "unstable". So i will pass on trying on my router for now, and await an update from your kind self. 

https://as-test.stephen304.com/chef/#2f236bdfa12b4b2

**Comment by Roland-B** [comment]
Any progress? Looking forward to being able to gen snapshots again..

**Comment by aparcar** [comment]
@Roland-B please try again

**Comment by Roland-B** [comment]
> 
> 
> @Roland-B please try again

Oikidoke, will do, thanks. 

Server showing as down at mo, will update you when I can :)

**Comment by Roland-B** [comment]
> 
> 
> @Roland-B please try again

Thanks @aparcar :) It now builds but states the image is "unstable". Am I safe to use this? I guess it is being flagged as unstable because its expecting the image to contain wpad-mini and not wpad-basic as part of the checks it makes after compiling?

**Comment by aparcar** [comment]
@Roland-B the unstable is added as you're using a snapshot. These are nightly builds with may fail to start or work at all. Therefore don't use them if you depend on them. It is not related to the package selection itself.
