### ISSUE TITLE
Using Chef RedINC Community Image

### ISSUE THREAD

**Issue by kleper** [aparcar/jefe#68]
When I try to generate a Libremesh image of the REDINC community I have the following error:
Unknown package in request: zz-redinc-comunitaria-hacklime

Y no permite generar la imagen.
Cuando hago la compilación manual usando el SDK no tengo problemas.

**Comment by aparcar** [comment]
@kleper sorry for the slow response, please try again.

**Comment by kleper** [comment]
Thanks, I already probe and it does not take error when I select the profile of the project but I do not know if the image that is generated if it has the configurations, I am going to test the images and I write.

**Comment by aparcar** [comment]
If the issue still exists, please reopen
