### ISSUE TITLE
Snapshot@WR741N - manifest_fail

### ISSUE THREAD

**Issue by Camis** [aparcar/jefe#69]
https://i.imgur.com/QTlgkh1.png

https://as-test.stephen304.com/download/faillogs/faillog-30fb9ac123ef.txt

**Comment by aparcar** [comment]
The issue should be fixed via https://github.com/aparcar/meta-imagebuilder/commit/c9187e5ec547bc0b25a01a095aa957e4afc8ff2e#diff-e9a23cbc455158951716b440c3d165e0R77
Please try again and close the issue if it works now

**Comment by aparcar** [comment]
Please reopen if the error still exists.
