### ISSUE TITLE
check the default settings for ppp and usb on ubnt

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#7]
when trying jefe f.i. for "Ubiquity Loco" there are packages for ppp and usb.
where does it come from? these devices dont habe USB

**Comment by aparcar** [comment]
thank you I'll check that

**Comment by aparcar** [comment]
using `make info`
```
Default Packages: [...] ppp ppp-mod-pppoe [...]

[...]

ubnt-loco-m-xw:
    Ubiquiti Loco XW
    Packages: kmod-usb-core kmod-usb2
```

The build-server only parses the output of the imagebuilders, is it possible the imagebuilder is setup bad? @dangowrt

Removing the packages from the "Edit packages" section results in an image without the packages :)

**Comment by aparcar** [comment]
@FreifunkUFO this seems to be a LEDE bug, please report it here: https://bugs.lede-project.org/

**Comment by dangowrt** [comment]
https://github.com/lede-project/source/blob/master/target/linux/ar71xx/image/ubnt.mk#L40

**Comment by FreifunkUFO** [comment]
seems to be configured by @blogic when reordering 
https://github.com/lede-project/source/commit/636089ead6864364798ac988299429d171051c0e#diff-8fd5a4a2c103925f08c02265642dc96e
