### ISSUE TITLE
How to chef image with "wpad" instead of "wpad-mini"

### ISSUE THREAD

**Issue by Camis** [aparcar/jefe#72]
I delete in "Edit Pacakges", "wpad-mini", and add "wpad" but i always got a error:

```
Collected errors:
 * check_conflicts_for: The following packages conflict with wpad-basic:
 * check_conflicts_for: 	wpad * 
 * opkg_install_cmd: Cannot install package wpad-basic.
```

https://as-test.stephen304.com/download/faillogs/faillog-da5dc5d35a31.txt

**Comment by Suxsem** [comment]
just press "edit packages" and add the following lines:
```
-wpad-mini
wpad
```
