### ISSUE TITLE
link to factory.bin image missing

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#75]
when baking firmware there is only a link to sysupgrade-bin, but i miss the factory-bin.
see also https://github.com/libremesh/chef/issues/3

**Comment by aparcar** [comment]
should be fixed via https://github.com/aparcar/attendedsysupgrade-server/commit/8597b744b9d90906248281172300076dcb13b46a and https://github.com/libremesh/chef/commit/bbda127c0d0a8f24cce84d870f33db812494c6e0

**Comment by FreifunkUFO** [comment]
thanks.
see https://github.com/libremesh/chef/issues/77 to fix your new feature
