### ISSUE TITLE
cannot select netgear ex3700/3800 with openwrt 18.06.02

### ISSUE THREAD

**Issue by DittelHome** [aparcar/jefe#76]
Hi,
cannot select netgear ex3700/3800 with openwrt 18.06.02.
Using 18.06.01 there is no problem

regards klaus

**Comment by aparcar** [comment]
Hey, thanks for reporting, when added the new version not all targets where compiled yet. The worker is currently updating and it should be available in a matter of minutes.

**Comment by aparcar** [comment]
https://chef.libremesh.org/#30d0015605225e4
