### ISSUE TITLE
clients should decide on their own if they want https or http

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#77]
where is the according enhancement-ticket?
https://github.com/aparcar/attendedsysupgrade-server/commit/8597b744b9d90906248281172300076dcb13b46a

nice feature, but not working atm. i cant download libremesh-images on a libremesh-node, there is a need for installing f.i. curl first.
please setup the chef.libremesh.org website to serve http. atm there is only a redirection to https, which fails on http-only-devices.

**Comment by aparcar** [comment]
Thanks, the certbot somewhat screwed the nginx file and left the redirect even after disabling it.
