### ISSUE TITLE
having an index.html file or rename chef.html

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#78]
there should be a standard-index page, perhaps index.html, because normally this project will be running in an subdir or a subdomain (so also a subdir on a server)

on https://github.com/libremesh/chef/issues/71 there was written:
>The installation is pretty straight forward, just put the files somewhere on a server and point a web server to open the chef.html

but that "pointing a web server to open the chef.html" would mean the need for editing webserver-config. i think there is no reason for that, no need to have an chef.html instead of standard- index.html.

**Comment by aparcar** [comment]
okay

**Comment by aparcar** [comment]
fixed via https://github.com/libremesh/chef/commit/c6d32316941d6a248fd8ce477a7b745e0fd78105
