### ISSUE TITLE
lime: wpad-mini vs. wpad-mesh

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/jefe#8]
when using the 11s flavour, an other wpad* is needed. the needed package is added, but wpad-mini isnt needed anymore

![teje-bug](https://user-images.githubusercontent.com/2579265/31637352-9f222aae-b2ce-11e7-845a-12e7b30f02e0.png)

**Comment by FreifunkUFO** [comment]
the extra package: https://github.com/libremesh/network-profiles/blob/master/libremesh/encrypt-11s/PACKAGES

the imagebuilder will get from jefe:

Packages: base-files busybox dropbear firewall fstools ip6tables iptables kmod-ath9k kmod-gpio-button-hotplug kmod-usb-core kmod-usb-ledtrig-usbport kmod-usb2 libc libgcc lime-full logd mtd netifd odhcp6c odhcpd opkg ppp ppp-mod-pppoe swconfig uboot-envtools uci uclient-fetch wpad-mini wpad-mesh base-files busybox dropbear firewall fstools ip6tables iptables kernel kmod-ath9k kmod-gpio-button-hotplug kmod-usb-core kmod-usb-ledtrig-usbport kmod-usb2 libc libgcc logd mtd netifd odhcp6c odhcpd opkg ppp ppp-mod-pppoe swconfig uboot-envtools uci uclient-fetch wpad-mini

see https://betaupdate.libremesh.org/static/lime/17.06/ar71xx/generic/tl-wr1043nd-v1/lime-17.06-4961fcbcd0d317f-libremesh-encrypt-11s-ar71xx-generic-tl-wr1043nd-v1-sysupgrade.bin.log

**Comment by aparcar** [comment]
does the lime-sdk/cooker behave the same way? it's possible to remove `wpad-mini` via *Edit packages*, tho it's not done automatically

**Comment by ilario** [comment]
related discussion on libremesh/lime-packages#208

**Comment by FreifunkUFO** [comment]
problem on jefe.tk: the additional packages are not shown to the user.

**Comment by aparcar** [comment]
yes, currently the packages are processed on the server side. I don't like that solution and will see if I can do something about it. however, a clean solution would be to auto remove the wpad-mini and this isn't supported for now with the PACKAGES concept

**Comment by aparcar** [comment]
this issue is out of scope for this project :(

**Comment by FreifunkUFO** [comment]
so what does it mean? problem is still existing. or do you want to delete libremesh as a supported "distribution"?

**Comment by aparcar** [comment]
@FreifunkUFO problem still exists but it's not a problem of _chef_. Using the official _lime-sdk_ results in an image with both `wpad-mesh` and `wpad-mini` installed. The problem are thedependencies/flavors that should be solved within LibreMesh and not individually by _chef_.

**Comment by ilario** [comment]
Can anyone open an issue on this on the correct repository? (lime-sdk?)

**Comment by aparcar** [comment]
@FreifunkUFO would you mind?

**Comment by FreifunkUFO** [comment]
@aparcar why is "this issue .. out of scope for this project :("?
otherwise please reopen ticket.
see also profile-changes https://github.com/libremesh/network-profiles/commit/5ab8abfc32f09b7f3ebfa81db2a1d01bc5b95c29
