### ISSUE TITLE
Save Device Model/Packages

### ISSUE THREAD

**Issue by vip9** [aparcar/jefe#81]
This option would allow to save device model and list of custom packages to localStorage, for faster setting up building.

**Comment by aparcar** [comment]
could you create a PR? I never touched local storage...

**Comment by vip9** [comment]
Could you please look at https://github.com/vip9/chef ?
For now, I am not familiar with API (because of limitation of searching full target) nor github PR-s's.

**Comment by aparcar** [comment]
https://betachef.libremesh.org/ please try here

**Comment by vip9** [comment]
Great!

**Comment by aparcar** [comment]
please test it and optimize the code if you like. I'll merge it once stable

**Comment by vip9** [comment]
Still not merged? It looks fine.
