### ISSUE TITLE
[Feature] Support LibreCMC

### ISSUE THREAD

**Issue by ghbjklhv** [aparcar/jefe#84]
**Feature**: Support [LibreCMC](https://www.wikipedia.org/wiki/LibreCMC)
**Why?**: LibreCMC is the most popular router operating system for free software devices, especially RYF certified devices. I think if LibreMesh could be compiled with LibeCMC it would make is significantly easier for free software projects to support LibreMesh.
**How?**: LibreCMC is actually very similar to OpenWRT. My understanding is that they often collaborate on software projects because of this.

_________________________

Wan to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75915817-feature-support-librecmc)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75915817)](https://www.bountysource.com/issues/75915817-feature-support-librecmc)

**Comment by ilario** [comment]
That's interesting but we would need to know more details about "very similar"/the small differences.
Do you have some list of differences?
For sure some modifications to lime-packages repository will be required.
On a first look seems that LibreCMC also uses UCI, and this is good.

**Comment by aparcar** [comment]
It looks like a rebranding of OpenWrt, I did not find a description point out the difference. Feel free to create a PR. ImageBuilders are required for support.

**Comment by ghbjklhv** [comment]
@ilario I'm unaware of such a list.

The key difference is that LibreCMC uses [`linux-libre`](https://gogs.librecmc.org/libreCMC/linux-libre) and [`linux-deblob`](https://gogs.librecmc.org/libreCMC/linux-deblob) scripts.
My understanding is that OpenWRT uses vanilla Linux.

Their source code is published here: https://gogs.librecmc.org/libreCMC/libreCMC

According to their FAQ:

> **What is libreCMC based upon?**
> 
> libreCMC GNU/linux-libre is a fork of the popular LEDE Project, but we use a linux-libre kernel and strip out some non-free components that are otherwise included in LEDE.
 
> **What is wrong with OpenWRT/LEDE?**
> 
> Some people have the view that everyone should have the freedom to control the software that runs on devices they own. If any compromises are made, then some of the benefits of Free Software go out the window. The OpenWRT/LEDE project does help give users more freedom than they would otherwise have, but some of the supported devices and packages are non-free. 

You may also be interested in this [Reddit thread](https://www.reddit.com/r/librecmc/comments/c4hx4f/what_changes_did_librecmc_make_after_forking/).

@aparcar I would have to assume this is what you mean:
https://gogs.librecmc.org/libreCMC/libreCMC/src/v1.4/target/imagebuilder

**Comment by aparcar** [comment]
I'll look into that next week

**Comment by aparcar** [comment]
@ghbjklhv could you ask the developer to work more closely together with upstream OpenWrt? Would be interesting to apply his kernel patchset etc to the currently running OpenWrt stack.

As a base, ImageBuilders are required to use Chef, without that, support is currently a no go.

**Comment by aparcar** [comment]
Closing due to lack of response. 

Please open ASU specific issues here: https://github.com/aparcar/asu/
Please open interface specific issues here: https://gitlab.com/openwrt/web/firmware-selector-openwrt-org

Chef is no longer developed.
