### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by chancat87** [aparcar/jefe#85]
Is the project still running? Why can't I open each of your websites?

![20191201012847](https://user-images.githubusercontent.com/25543219/69903870-42a30680-13da-11ea-9e8e-6df7dc63484a.jpeg)

**Comment by aparcar** [comment]
Yes i got multiple requests for a new setup already. I'll try to fix it within the next week

**Comment by chancat87** [comment]
> 是的，我已经有多个要求进行新设置的请求。我会在下周内尝试修复

Thank you for reply.

**Comment by aparcar** [comment]
Uh oh sorry for the slow response! Please check the new front end at chef.libremesh.org/

**Comment by FreifunkUFO** [comment]
error 
`AssertionError: Wrong ImageBuilder archive checksum`
on that web-page
linked to a new try of project 
https://github.com/mwarning/yet_another_firmware_selector

**Comment by aparcar** [comment]
Please open ASU specific issues here: https://github.com/aparcar/asu/
Please open interface specific issues here: https://gitlab.com/openwrt/web/firmware-selector-openwrt-org

Chef is no longer developed.
