### ISSUE TITLE
Languages missing from language selector

### ISSUE THREAD

**Issue by Nikerabbit** [aparcar/jefe#88]
The language selector in https://chef.libremesh.org/ is missing many languages present in https://github.com/translation-bridge/chef/tree/master/i18n. Why is this?

**Comment by ilario** [comment]
@patogit

**Comment by aparcar** [comment]
What you see on the Chef domains is actually https://gitlab.com/openwrt/web/firmware-selector-openwrt-org

Chef is no longer developed. @mwarning coordinates the new web interface and the files to translate are found [here](https://gitlab.com/openwrt/web/firmware-selector-openwrt-org/-/blob/master/www/i18n.js)
